# Generated by Django 4.2.26 on 2025-12-03 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_dislike"),
    ]

    operations = [
        migrations.CreateModel(
            name="ABTestButtonClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("A", "Variant A (kudos)"),
                            ("B", "Variant B (thanks)"),
                        ],
                        max_length=1,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "A/B Test Button Click",
                "verbose_name_plural": "A/B Test Button Clicks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ABTestPageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "variant",
                    models.CharField(
                        choices=[
                            ("A", "Variant A (kudos)"),
                            ("B", "Variant B (thanks)"),
                        ],
                        max_length=1,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "A/B Test Page View",
                "verbose_name_plural": "A/B Test Page Views",
                "ordering": ["-created_at"],
            },
        ),
    ]
